# Generated by Django 5.2.4 on 2025-07-13 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_created_at_farmer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 14, 10, 8, 135500, tzinfo=datetime.timezone.utc)),
        ),
    ]
