# Generated by Django 5.2.4 on 2025-07-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_farmer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 17, 17, 25, 673379, tzinfo=datetime.timezone.utc)),
        ),
    ]
