# Generated by Django 5.2.4 on 2025-07-15 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_farmer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 20, 23, 18, 847283, tzinfo=datetime.timezone.utc)),
        ),
    ]
